DROP TABLE IF EXISTS CATEGORIAS;
CREATE TABLE CATEGORIAS (
	CODIGO_CAT SERIAL NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CATEGORIA_PADRE INT,
	CONSTRAINT CATEGORIAS_PK PRIMARY KEY (CODIGO_CAT),
	CONSTRAINT CATEGORIAS_FK FOREIGN KEY (CATEGORIA_PADRE) REFERENCES CATEGORIAS (CODIGO_CAT)
)

