--------------------------------------------------------------------
--CREACION DE TABLAS PARA PRONOSTICOS DE PARTIDOS DE LA COPA AMERICA
--------------------------------------------------------------------
--ELIMINACION DE TABLAS
DROP TABLE IF EXISTS T_PRONOSTICO;
DROP TABLE IF EXISTS T_USUARIO;
DROP TABLE IF EXISTS T_PARTIDO;
DROP TABLE IF EXISTS T_EQUIPO;

--EQUIPOS PARTICIPANTES DE LA COPA AMERICA
CREATE TABLE T_EQUIPO (
	CODIGO VARCHAR(3) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CONSTRAINT T_EQUIPO_PK PRIMARY KEY (CODIGO)
);

--PARTIDOS DE LA COMPETICION
CREATE TABLE T_PARTIDO (
	ID SERIAL NOT NULL,
	EQUIPO_A VARCHAR(3) NOT NULL,
	EQUIPO_B VARCHAR(3) NOT NULL,
	FECHA TIMESTAMP NOT NULL,
	CONSTRAINT T_PARTIDO_PK PRIMARY KEY (ID),
	CONSTRAINT T_PARTIDO_T_EQUIPO_A_FK FOREIGN KEY (EQUIPO_A) REFERENCES T_EQUIPO (CODIGO),
	CONSTRAINT T_PARTIDO_T_EQUIPO_B_FK FOREIGN KEY (EQUIPO_B) REFERENCES T_EQUIPO (CODIGO)
);

--USUARIOS DE LA APLICACION
CREATE TABLE T_USUARIO (
	CEDULA VARCHAR(30) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	CONSTRAINT T_USUARIO_PK PRIMARY KEY (CEDULA)
);

--PRONOSTICOS
CREATE TABLE T_PRONOSTICO (
	ID SERIAL NOT NULL,
	USUARIO VARCHAR(30) NOT NULL,
	PARTIDO INT NOT NULL,
	EQUIPO_A VARCHAR(3) NOT NULL,
	EQUIPO_B VARCHAR(3) NOT NULL,
	MARCADOR_EQ_A INT NOT NULL,
	MARCADOR_EQ_B INT NOT NULL,
	CONSTRAINT T_PRONOSTICO_PK PRIMARY KEY (ID),
	CONSTRAINT T_PRONOSTICO_T_USUARIO_FK FOREIGN KEY (USUARIO) REFERENCES T_USUARIO (CEDULA),
	CONSTRAINT T_PRONOSTICO_T_PARTIDO_FK FOREIGN KEY (PARTIDO) REFERENCES T_PARTIDO (ID),
	CONSTRAINT T_PRONOSTICO_T_EQUIPO_A_FK FOREIGN KEY (EQUIPO_A) REFERENCES T_EQUIPO (CODIGO),
	CONSTRAINT T_PRONOSTICO_T_EQUIPO_B_FK FOREIGN KEY (EQUIPO_B) REFERENCES T_EQUIPO (CODIGO)
);